name: Docker Release

on:
  workflow_dispatch:

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      REPO: aoozdemir/vops-python-app

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u aoozdemir -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO -a
