name: Rollout

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      REPO: aoozdemir/vops-python-app
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u aoozdemir -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO -a

  update:
    name: Update Kube Resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.CLUSTER_API_ENDPOINT }}
          k8s-secret: ${{ secrets.CLUSTER_GHA_SECRET }}
      - run: |
          kubectl apply -f ./kubernetes/resources/mysql-storage.yml

  rollout:
    name: Rollout Changes to Kubernetes
    runs-on: ubuntu-latest
    needs: [build, update]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.CLUSTER_API_ENDPOINT }}
          k8s-secret: ${{ secrets.CLUSTER_GHA_SECRET }}
      - run: |
          kubectl apply -f ./kubernetes/app/application-manifest.yml
